### ISSUE TITLE
prompt not displayed at boot

### ISSUE THREAD

**Issue by fariouche** [bradschl/embedded-c-debug-console#2]
Hello,

I know this repo was not updated since a long time, but I would like to say that the prompt is not displayed at boot. I need to input a character to see it.

I've modified the code a bit by replacing the line
console->state = state_wait_for_client;
by the line
console->state = state_start_new_command;

And now the prompt is displayed.... I don't see any drawback but I'm not sure because of this term_set_snoop_char() that will not be called at boot anymore

Thanks!

**Comment by bradschl** [comment]
Hello @fariouche 
The default behavior of not displaying the prompt until the terminal sends characters was to allow for boot up messages and log statements to be printed. So, until the user starts interacting with the prompt it stays silent and in the background.

Your modification will work fine if that's the behavior you want, no need to worry about the snoop buffer. The snoop buffer is used when a state reads a character and then decides that a different state needs to handle it. So, the original state pushes the character onto snoop, switches state, and the new state reads that character back out of the snoop buffer and takes action.

Hope that helps

**Comment by fariouche** [comment]
thank you very much for the quick and clear explanation!
